// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PwHashTypeT string

const (
	PwHashTypeTArgon2id PwHashTypeT = "argon2id"
)

func (e *PwHashTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PwHashTypeT(s)
	case string:
		*e = PwHashTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for PwHashTypeT: %T", src)
	}
	return nil
}

type NullPwHashTypeT struct {
	PwHashTypeT PwHashTypeT
	Valid       bool // Valid is true if PwHashTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPwHashTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.PwHashTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PwHashTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPwHashTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PwHashTypeT), nil
}

type User struct {
	ID         uuid.UUID
	CreatedAt  pgtype.Timestamptz
	Username   string
	PwHashType PwHashTypeT
	PwHash     string
}
