// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearOtherSessionTokensForUser = `-- name: ClearOtherSessionTokensForUser :exec
DELETE FROM session_tokens
WHERE for_user = $1
  AND id != $2
`

type ClearOtherSessionTokensForUserParams struct {
	ForUser uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) ClearOtherSessionTokensForUser(ctx context.Context, arg ClearOtherSessionTokensForUserParams) error {
	_, err := q.db.Exec(ctx, clearOtherSessionTokensForUser, arg.ForUser, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, pw_hash_type, pw_hash)
VALUES ($1, $2, $3)
RETURNING id, created_at, username, pw_hash_type, pw_hash
`

type CreateUserParams struct {
	Username   string
	PwHashType PwHashTypeT
	PwHash     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PwHashType, arg.PwHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.PwHashType,
		&i.PwHash,
	)
	return i, err
}

const deleteBlockRelation = `-- name: DeleteBlockRelation :execrows
DELETE FROM block_relations
WHERE origin_user = $1
  AND blocked_user = $2
`

type DeleteBlockRelationParams struct {
	OriginUser  uuid.UUID
	BlockedUser uuid.UUID
}

func (q *Queries) DeleteBlockRelation(ctx context.Context, arg DeleteBlockRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockRelation, arg.OriginUser, arg.BlockedUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionToken = `-- name: DeleteSessionToken :execrows
DELETE FROM session_tokens
WHERE id = $1
`

func (q *Queries) DeleteSessionToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserBlockList = `-- name: GetUserBlockList :many
SELECT u.id, u.created_at, u.username, u.pw_hash_type, u.pw_hash
FROM block_relations br
JOIN users u ON u.id = br.blocked_user
WHERE origin_user = $1
`

func (q *Queries) GetUserBlockList(ctx context.Context, originUser uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserBlockList, originUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.PwHashType,
			&i.PwHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, username, pw_hash_type, pw_hash FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.PwHashType,
		&i.PwHash,
	)
	return i, err
}

const insertBlockRelation = `-- name: InsertBlockRelation :exec
INSERT INTO block_relations (origin_user, blocked_user)
VALUES ($1, $2)
`

type InsertBlockRelationParams struct {
	OriginUser  uuid.UUID
	BlockedUser uuid.UUID
}

func (q *Queries) InsertBlockRelation(ctx context.Context, arg InsertBlockRelationParams) error {
	_, err := q.db.Exec(ctx, insertBlockRelation, arg.OriginUser, arg.BlockedUser)
	return err
}

const insertSessionToken = `-- name: InsertSessionToken :exec
INSERT INTO session_tokens (for_user, token, expires_at)
VALUES ($1, $2, $3)
`

type InsertSessionTokenParams struct {
	ForUser   uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) InsertSessionToken(ctx context.Context, arg InsertSessionTokenParams) error {
	_, err := q.db.Exec(ctx, insertSessionToken, arg.ForUser, arg.Token, arg.ExpiresAt)
	return err
}

const lookupSessionTokenWithUser = `-- name: LookupSessionTokenWithUser :one
SELECT st.id, st.created_at, st.for_user, st.token, st.expires_at,
    u.id AS user_id,
    u.created_at AS user_created_at,
    u.username AS user_username,
    u.pw_hash_type AS user_pw_hash_type,
    u.pw_hash AS user_pw_hash
FROM session_tokens st
JOIN users u ON u.id = st.for_user
WHERE token = $1
  AND expires_at > CURRENT_TIMESTAMP
`

type LookupSessionTokenWithUserRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	ForUser        uuid.UUID
	Token          string
	ExpiresAt      time.Time
	UserID         uuid.UUID
	UserCreatedAt  time.Time
	UserUsername   string
	UserPwHashType PwHashTypeT
	UserPwHash     string
}

func (q *Queries) LookupSessionTokenWithUser(ctx context.Context, token string) (LookupSessionTokenWithUserRow, error) {
	row := q.db.QueryRow(ctx, lookupSessionTokenWithUser, token)
	var i LookupSessionTokenWithUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ForUser,
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
		&i.UserCreatedAt,
		&i.UserUsername,
		&i.UserPwHashType,
		&i.UserPwHash,
	)
	return i, err
}

const updateSessionTokenExpiry = `-- name: UpdateSessionTokenExpiry :exec
UPDATE session_tokens
SET expires_at = $2
WHERE id = $1
`

type UpdateSessionTokenExpiryParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) UpdateSessionTokenExpiry(ctx context.Context, arg UpdateSessionTokenExpiryParams) error {
	_, err := q.db.Exec(ctx, updateSessionTokenExpiry, arg.ID, arg.ExpiresAt)
	return err
}
