// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (
  name, display_name
) VALUES (
  $1, $2
)
RETURNING id, name, display_name
`

type CreateExampleParams struct {
	Name        string
	DisplayName pgtype.Text
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRow(ctx, createExample, arg.Name, arg.DisplayName)
	var i Example
	err := row.Scan(&i.ID, &i.Name, &i.DisplayName)
	return i, err
}
